# Generated by Django 6.0.6 on 2026-07-02 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fqn", models.CharField(db_index=True, max_length=1024, unique=True)),
                ("name", models.CharField(max_length=512)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("DATABASE", "Database"),
                            ("SCHEMA", "Schema"),
                            ("TABLE", "Table"),
                            ("VIEW", "View"),
                            ("COLUMN", "Column"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "entities",
                "ordering": ["fqn"],
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_name", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_current", models.IntegerField(default=0)),
                ("progress_total", models.IntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdentifiableInfo",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="identifiable_info",
                        serialize=False,
                        to="catalog.entity",
                    ),
                ),
                ("phi_score", models.IntegerField(default=0)),
                ("pii_score", models.IntegerField(default=0)),
                ("pass_stage", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "identifiable info",
                "verbose_name_plural": "identifiable info",
            },
        ),
        migrations.CreateModel(
            name="IdentifiableInfoBooster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boost_type", models.CharField(max_length=50)),
                ("boost_score", models.IntegerField(default=5)),
                (
                    "primary_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_boosters",
                        to="catalog.entity",
                    ),
                ),
                (
                    "secondary_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_boosters",
                        to="catalog.entity",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("primary_entity", "secondary_entity", "boost_type")
                },
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_entity_type",
                    models.CharField(
                        choices=[
                            ("DATABASE", "Database"),
                            ("SCHEMA", "Schema"),
                            ("TABLE", "Table"),
                            ("VIEW", "View"),
                            ("COLUMN", "Column"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_entity_type",
                    models.CharField(
                        choices=[
                            ("DATABASE", "Database"),
                            ("SCHEMA", "Schema"),
                            ("TABLE", "Table"),
                            ("VIEW", "View"),
                            ("COLUMN", "Column"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("CONTAINS", "Contains"),
                            ("BELONGS_TO", "Belongs To"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="catalog.entity",
                    ),
                ),
                (
                    "to_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="catalog.entity",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_entity", "to_entity", "relation")},
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256)),
                ("value", models.CharField(blank=True, default="", max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="catalog.entity",
                    ),
                ),
            ],
            options={
                "unique_together": {("entity", "key", "value")},
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_name", models.CharField(max_length=256)),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("operations", "Operations"),
                            ("language", "Language"),
                            ("sentinel", "Sentinel"),
                        ],
                        default="language",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("pass_stage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="catalog.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "term_name"],
                "unique_together": {("entity", "term_name", "term_type")},
            },
        ),
    ]
